### ISSUE TITLE
Security Concerns

### ISSUE THREAD

**Issue by TsgabiXD** [Bill-Stewart/SyncthingWindowsSetup#34]
I just want you to know that VirusTotal is issuing some red flags:
![grafik](https://github.com/user-attachments/assets/aff7a505-5cf7-482f-9db9-a01236468949)
https://www.virustotal.com/gui/file/fac31c2c48b5211ca839fded7965b61dec9c9de424ea20440c12ff643d131fca

I hope there is no serious problem.

And also thank's for that awesome piece of software ^~^

**Comment by Bill-Stewart** [comment]
These are false-positives. If you review past issues for this project, you will see that that overwhelming majority of them are due to anti-malware false-positives. It's simply not possible for anti-malware software to be 100% foolproof against false positives (despite their claims to the contrary). If your anti-malware program is complaining, report the installer to your anti-malware software as a false-positive, and it's possible they might fix it. If they don't, you can whitelist the installer.
