### ISSUE TITLE
Setup initialization error, how can I fix it?

### ISSUE THREAD

**Issue by nori00000** [Bill-Stewart/SyncthingWindowsSetup#53]
The WSH script registration is invalid.
To fix this issue, see the “Setup initialization errors” section of the documentation.
The installation should now end.

![image](https://github.com/user-attachments/assets/3bf17b8c-3cca-46c8-b54a-d59bc22aad1d)

The environment is windows.

Here's a capture of the windows environment variable window.

![image](https://github.com/user-attachments/assets/ad6d1ad1-01eb-471f-a1f9-bd1ee9cf4f69)

**Comment by jameswilliamknight** [comment]
Seeing the same

![image](https://github.com/user-attachments/assets/9aa66521-fe25-4900-acfd-1b37736d6493)

**Comment by Bill-Stewart** [comment]
![Syncthing_Windows_Setup_script_registration_error](https://github.com/user-attachments/assets/ee750beb-53ce-4846-9d33-380e8c9956a8)

As the message says, please read the [Setup Initialization Errors](https://github.com/Bill-Stewart/SyncthingWindowsSetup/?tab=readme-ov-file#setup-initialization-errors) section in the [documentation](https://github.com/Bill-Stewart/SyncthingWindowsSetup/) because it tells you exactly what to do.

**Comment by Wasabiboy** [comment]
Have we found a work around yet?

**Comment by Bill-Stewart** [comment]
The "workaround" is to fix the broken registry value [as described in the documentation](https://github.com/Bill-Stewart/SyncthingWindowsSetup#setup-initialization-errors).
